### ISSUE TITLE
highlight doesn't work

### ISSUE THREAD

**Issue by tjx666** [IronGeek/vscode-env#3]
@IronGeek 

version info: 

```
Version: 1.57.0-insider (Universal)
Commit: 217f1a2f60a197807de78af362ecb832100fda96
Date: 2021-06-02T05:12:39.349Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0
```

![image](https://user-images.githubusercontent.com/41773861/120516138-9e03e980-c401-11eb-932a-187069d8296f.png)

**Comment by IronGeek** [comment]
Hi, thank you for reporting the issue...

I've tried testing the extension using the latest Visual Studio Code Insiders running on linux:
```
Version: 1.57.0-insider
Commit: 20df87725d3ce4a501187f0240c2f159aa0ad2a5
Date: 2021-06-03T06:01:30.344Z
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.8.0-53-generic
```
![Selection_557](https://user-images.githubusercontent.com/1383932/120679103-01098500-c4c3-11eb-8e78-869fe30c9d44.png)

And everything seems to be normal on my part. 

The only probable cause I could  think of for this issue is the new **trusted workspaces feature** which are enabled on Visual Studio Code Insiders. Could you verify that the extensions is indeed installed and activated...?
> You may need to trust the currently opened workspace, since the current release is not yet updated to run on restricted mode

**Comment by tjx666** [comment]
Seems not to be activate. @IronGeek 

![image](https://user-images.githubusercontent.com/41773861/120736283-9423d880-c51e-11eb-90ba-36a8a3cced05.png)

![Uploading image.png…]()

**Comment by IronGeek** [comment]
@tjx666 does it work if all other extensions disabled?

**Comment by tjx666** [comment]
@IronGeek
Seems to works.

![image](https://user-images.githubusercontent.com/41773861/120758413-65b8f400-c544-11eb-93b6-faa1b7c8e9dc.png)

**Comment by IronGeek** [comment]
Great...!    So, I think there might be some conflict between this extension and one of your other installed extensions.

If you don't mind, could you try finding out what the _bad extension_ is? or if it's not too much too ask could you post your installed extensions here? 

You could use the `code --list-extensions` or `code-insiders --list-extensions` command from the terminal to list the installed extensions.

**Comment by tjx666** [comment]
```
  ~/code/DataDiDi   ytj_dev                                                                                                                                       
❯ code-insiders --list-extensions
aaron-bond.better-comments
adam-bender.commit-message-editor
BendixMa.dart-data-class-generator
benjaminadk.emojis4git
bierner.color-info
bierner.emojisense
bierner.gif-player
bierner.jsdoc-markdown-highlighting
bodil.file-browser
chrisdias.vscode-opennewinstance
codezombiech.gitignore
Dart-Code.dart-code
Dart-Code.flutter
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
developer2006.svg-gallery
donjayamanne.githistory
dsznajder.es7-react-js-snippets
dtsvet.vscode-wasm
dzhavat.css-initial-value
eamodio.gitlens-insiders
ecmel.vscode-html-css
EditorConfig.EditorConfig
eg2.vscode-npm-script
esbenp.prettier-vscode
formulahendry.code-runner
foxundermoon.shell-format
Gruntfuggly.todo-tree
hediet.vscode-drawio
ionutvmi.path-autocomplete
IronGeek.vscode-env
jakearl.search-editor-apply-changes
jbenden.c-cpp-flylint
jeff-hykin.better-cpp-syntax
jjaakko.markdown-kbd
jock.svg
kamikillerto.vscode-colorize
kisstkondoros.vscode-gutter-preview
L13RARY.l13-diff
meganrogge.template-string-converter
mhutchie.git-graph
mkxml.vscode-filesize
mrmlnc.vscode-scss
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.hexeditor
ms-vscode.vscode-js-profile-flame
ms-vscode.vscode-typescript-next
msjsdiag.debugger-for-chrome
naco-siren.gradle-language
Nash.awesome-flutter-snippets
pflannery.vscode-versionlens
pomber.git-file-history
pomdtr.excalidraw-editor
pranaygp.vscode-css-peek
qcz.text-power-tools
redhat.vscode-yaml
robole.snippets-ranger
ryu1kn.partial-diff
shd101wyy.markdown-preview-enhanced
sleistner.vscode-fileutils
streetsidesoftware.code-spell-checker
stylelint.vscode-stylelint
thzt.vscode-ast
twxs.cmake
Tyriar.luna-paint
uctakeoff.vscode-counter
ultram4rine.vscode-choosealicense
VisualStudioExptTeam.vscodeintellicode
vscode-icons-team.vscode-icons
WallabyJs.quokka-vscode
xabikos.JavaScriptSnippets
YuTengjing.open-in-external-app
YuTengjing.view-github-repository
YuTengjing.vscode-fe-helper
yzhang.markdown-all-in-one
zenghongtu.vscode-asciiflow2
zhaouv.vscode-markdown-draw
```

**Comment by tjx666** [comment]
@IronGeek 
I will try to find the conflicted extension tonight after day work.

**Comment by tjx666** [comment]
@IronGeek 

![image](https://user-images.githubusercontent.com/41773861/120820765-68890880-c587-11eb-9c59-ae5fe8663002.png)

**Comment by IronGeek** [comment]
@tjx666 Thank you for finding the conflicted extension.

It seems Visual Studio Code prefers activating `shell-format` extension over `ENV` for `.env` files.
AFAIK, there's no way to specify the extension load precedence/ priority from the extension itself... So there's really nothing I could do here.

You could however force the language of `.env` files to be always specified as `Environment Variables` (language id: **env**) using the Visual Studio Code `files.associations` settings:

![Selection_560](https://user-images.githubusercontent.com/1383932/120843000-bd347f80-c597-11eb-85ea-b2cd7b61f378.png)

Or use the `Select Language Mode` button on the Visual Studio Code status bar, for non permanent changes:

![Selection_565](https://user-images.githubusercontent.com/1383932/120843015-c58cba80-c597-11eb-9c3e-a7774d6e811f.png)

**Comment by tjx666** [comment]
It would be better to add `file. associations ` setting when install this extension, or suggest user to do this

**Comment by IronGeek** [comment]
I'll add this issue and workaround with `files.associations` as known issue to the README.

But IMO, setting the `files.associations` automatically  when the extension is installed (if it can be done) would be too intrusive.
The settings precedes all other default associations, so I think it should be left to be configured manually by each user...
