### ISSUE TITLE
Extention not activating

### ISSUE THREAD

**Issue by DavinderJolly** [IronGeek/vscode-env#6]
i don't know if  this is an issue specific to me but  my vs code by default sets **.env** files as **dotenv** language instead of **env**
so onLanguage:env never triggers

**Comment by LW901** [comment]
Hi @DavinderJolly,

I had the same issue. The solution I found was to change the file language from _env_ to _Environment Variables_ in the bottom right of VS Code.

Prior to fix -
![image](https://user-images.githubusercontent.com/91727480/149606235-2a80c324-4efe-4c02-a340-3df6d3299b6d.png)
![image](https://user-images.githubusercontent.com/91727480/149606298-b46d1e6e-4140-4540-981e-56a6168324e6.png)

Click on _env_ and change to _Environment Variables_ 
![image](https://user-images.githubusercontent.com/91727480/149606292-d7f0fa65-cdf3-428c-a461-415c1fe63341.png)

Working -
![image](https://user-images.githubusercontent.com/91727480/149606309-d34a895e-460a-46ec-be75-3f27d5349f1a.png)
![image](https://user-images.githubusercontent.com/91727480/149606313-57f945aa-f768-4163-9919-e7eff6e8104d.png)

**Comment by DavinderJolly** [comment]
> Hi @DavinderJolly,
> 
> I had the same issue. The solution I found was to change the file language from _env_ to _Environment Variables_ in the bottom right of VS Code.
> 
> Prior to fix - ![image](https://user-images.githubusercontent.com/91727480/149606235-2a80c324-4efe-4c02-a340-3df6d3299b6d.png) ![image](https://user-images.githubusercontent.com/91727480/149606298-b46d1e6e-4140-4540-981e-56a6168324e6.png)
> 
> Click on _env_ and change to _Environment Variables_ ![image](https://user-images.githubusercontent.com/91727480/149606292-d7f0fa65-cdf3-428c-a461-415c1fe63341.png)
> 
> Working - ![image](https://user-images.githubusercontent.com/91727480/149606309-d34a895e-460a-46ec-be75-3f27d5349f1a.png) ![image](https://user-images.githubusercontent.com/91727480/149606313-57f945aa-f768-4163-9919-e7eff6e8104d.png)

i saw that but i'd much rather stay with the default and this extension didn't seem interested in working for both so i just made my own local copy with the extension changed
