### ISSUE TITLE
Optional Double Hash Comment

### ISSUE THREAD

**Issue by Bro3Simon** [IronGeek/vscode-env#7]
It would be nice to be able to use a double hash comment for organizing and giving titles for different sections in the .env and it be treated different than a standard comment.

![image](https://user-images.githubusercontent.com/38329927/138344583-c79c6d1f-3732-4aa8-8ddc-a0ffc369cbb7.png)

**Comment by nandgator** [comment]
You can do that

![image](https://user-images.githubusercontent.com/38415384/155455195-86a1eee4-8cf8-4ab4-a7f2-beb5ea651f7e.png)
